#ifndef ASM_VM_CONSTANTS_H
#define ASM_VM_CONSTANTS_H

#endif //ASM_VM_CONSTANTS_H

#define MAX_COMMANDS 16384 //2^14
#define MAX_LABEL_LENGTH 21
#define MAX_LINE_LENGTH 44
#define COMMAND_NAMES 23
#define MAX_COMMAND_LENGTH 7
#define REGISTER_TYPES 6
#define MAX_REGISTER_TYPE_LENGTH 5